### ISSUE TITLE
sink._addParentTeardownLogic is not a function

### ISSUE THREAD

**Issue by dataangel** [nuonuoge/ionic4_angular6_elm#4]
不知为何报这个错

**Comment by nuonuoge** [comment]
信息太少，看不出来

**Comment by dataangel** [comment]
G:\ionic4-web>ionic build
> ng run app:build
sink._addParentTeardownLogic is not a function
TypeError: sink._addParentTeardownLogic is not a function
    at Observable.subscribe (G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:27:18)
    at MergeMapOperator.call (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at G:\ionic4-web\node_modules\rxjs\internal\util\subscribeToObservable.js:10:20
    at Object.subscribeToResult (G:\ionic4-web\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
    at MergeMapSubscriber._next (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (G:\ionic4-web\node_modules\rxjs\internal\Subscriber.js:64:18)
    at Observable._subscribe (G:\ionic4-web\node_modules\rxjs\internal\observable\scalar.js:6:20)
    at Observable._trySubscribe (G:\ionic4-web\node_modules\rxjs\internal\Observable.js:43:25)
    at Observable.subscribe (G:\ionic4-web\node_modules\rxjs\internal\Observable.js:29:22)
    at MergeMapOperator.call (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (G:\ionic4-web\node_modules\rxjs\internal\Observable.js:24:22)
    at MergeMapOperator.call (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (G:\ionic4-web\node_modules\rxjs\internal\Observable.js:24:22)
[ERROR] An error occurred while running subprocess ng.

        ng run app:build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by dataangel** [comment]
ionic CLI 4.1.2  Angular CLI: 6.0.8

**Comment by dataangel** [comment]
G:\ionic4-web>npm start

> elm@0.0.1 start G:\ionic4-web
> ng serve --port 5555 --proxy-config proxy.config.json

** Angular Live Development Server is listening on localhost:5555, open your browser on http://localhost:5555/ **
G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:27
            sink._addParentTeardownLogic(this.source || (config_1.config.useDeprecatedSynchronousErrorHandling && !sink.syncErrorThrowable) ?
                 ^

TypeError: sink._addParentTeardownLogic is not a function
    at Observable.subscribe (G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:27:18)
    at MergeMapOperator.call (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:35:23)
    at Observable.subscribe (G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at MapOperator.call (G:\ionic4-web\node_modules\rxjs\internal\operators\map.js:29:23)
    at Observable.subscribe (G:\ionic4-web\node_modules\@angular\cli\node_modules\rxjs\internal\Observable.js:24:22)
    at G:\ionic4-web\node_modules\rxjs\internal\util\subscribeToObservable.js:10:20
    at Object.subscribeToResult (G:\ionic4-web\node_modules\rxjs\internal\util\subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:72:14)
    at MergeMapSubscriber._next (G:\ionic4-web\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (G:\ionic4-web\node_modules\rxjs\internal\Subscriber.js:64:18)
    at TapSubscriber._next (G:\ionic4-web\node_modules\rxjs\internal\operators\tap.js:62:26)
    at TapSubscriber.Subscriber.next (G:\ionic4-web\node_modules\rxjs\internal\Subscriber.js:64:18)
    at portfinder.getPort (G:\ionic4-web\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\check-port.js:26:21)
    at G:\ionic4-web\node_modules\portfinder\lib\portfinder.js:190:16
    at G:\ionic4-web\node_modules\async\lib\async.js:52:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.0.1 start: `ng serve --port 5555 --proxy-config proxy.config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dataangel\AppData\Roaming\npm-cache\_logs\2018-09-10T19_46_25_421Z-debug.log

**Comment by dataangel** [comment]
应该是rxjs的问题

**Comment by nuonuoge** [comment]
https://github.com/ionic-team/ionic/issues/15478
追踪这个单子吧，ionic cli的问题

**Comment by nuonuoge** [comment]
https://github.com/ionic-team/ionic-cli/issues/3565
追踪这个单子吗，官方目前好像还没解决

**Comment by nuonuoge** [comment]
ionic-team/ionic-cli#3565
追踪这个单子吧，官方目前好像还没解决

**Comment by dataangel** [comment]
好的~~~
